// <auto-generated />
using System;
using IntelligentCarManagement.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IntelligentCarManagement.DataAccess.Migrations
{
    [DbContext(typeof(CarMngContext))]
    [Migration("20210729122604_Car_User_Driver")]
    partial class Car_User_Driver
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IntelligentCarManagement.DataAccess.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DriverID")
                        .HasColumnType("int");

                    b.Property<string>("FuelType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DriverID")
                        .IsUnique();

                    b.ToTable("Car");
                });

            modelBuilder.Entity("IntelligentCarManagement.DataAccess.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddressID")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressID")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("IntelligentCarManagement.DataAccess.Models.UserAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("IntelligentCarManagement.DataAccess.Models.Client", b =>
                {
                    b.HasBaseType("IntelligentCarManagement.DataAccess.Models.User");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("IntelligentCarManagement.DataAccess.Models.Driver", b =>
                {
                    b.HasBaseType("IntelligentCarManagement.DataAccess.Models.User");

                    b.Property<int>("DeservedClients")
                        .HasColumnType("int");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<byte[]>("License")
                        .HasColumnType("varbinary(max)");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.ToTable("Driver");
                });

            modelBuilder.Entity("IntelligentCarManagement.DataAccess.Models.Car", b =>
                {
                    b.HasOne("IntelligentCarManagement.DataAccess.Models.Driver", "Driver")
                        .WithOne("Car")
                        .HasForeignKey("IntelligentCarManagement.DataAccess.Models.Car", "DriverID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("IntelligentCarManagement.DataAccess.Models.User", b =>
                {
                    b.HasOne("IntelligentCarManagement.DataAccess.Models.UserAddress", "Address")
                        .WithOne("User")
                        .HasForeignKey("IntelligentCarManagement.DataAccess.Models.User", "AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("IntelligentCarManagement.DataAccess.Models.Client", b =>
                {
                    b.HasOne("IntelligentCarManagement.DataAccess.Models.User", null)
                        .WithOne()
                        .HasForeignKey("IntelligentCarManagement.DataAccess.Models.Client", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IntelligentCarManagement.DataAccess.Models.Driver", b =>
                {
                    b.HasOne("IntelligentCarManagement.DataAccess.Models.User", null)
                        .WithOne()
                        .HasForeignKey("IntelligentCarManagement.DataAccess.Models.Driver", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IntelligentCarManagement.DataAccess.Models.UserAddress", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("IntelligentCarManagement.DataAccess.Models.Driver", b =>
                {
                    b.Navigation("Car");
                });
#pragma warning restore 612, 618
        }
    }
}
